### ISSUE TITLE
Usage Instructions?

### ISSUE THREAD

**Issue by momo-the-monster** [benMcChesney/ofxKinect_ProjectSurfaces#1]
Hi Ben! Thanks for putting this out there, looks very cool. I managed to get it compiled and running, I see the camera input and can play with the thresholds, etc - but I'm a bit lost as to how the calibration works.
When I turn off the GUI and drag my mouse over the image, I crash with a SIGABRT. Here's what I get in the console: (using latest theo ofxKinect and 0073):

[Stream 70] Expected 1748 data bytes, but got 948
[error] in =, ROI mismatch
OpenCV Error: Incorrect size of input array (Non-positive cols or rows) in cvInitMatHeader, file     /Users/theo/Downloads/OpenCV-2.3.1/modules/core/src/array.cpp, line 146
terminate called throwing an exception(lldb) 

It seems to be happening because of line 95 in testApp::update():

contourFinder.findContours(grayImage, minBlobSize, maxBlobSize, maxBlobs , bFindContourHoles );

**Comment by benMcChesney** [comment]
Hi There !

It looks like the error is caused by there being no ROI or the ROI does not matchup. I'll take a look at it and try to get a fix out within a few days. Be sure to draw a rectangle on the "projector" area too see how it matches up. I'll be adding in some better step by step instructions, thanks for the issue !

**Comment by momo-the-monster** [comment]
Is the projector area off to the right? Do you stretch your window to show up on the projector? Should I just wait for the instructions? :)

**Comment by benMcChesney** [comment]
I'd wait for instructions :) I'll do what I can do dig around and see what's what

**Comment by benMcChesney** [comment]
Hey there :) I pushed a new build to master branch. I split up my development efforts between openNI and ofxKinect I still have plans to improve it in the future but for now it should be usable !
